pipeline {
    agent any

    stages {
        stage("Build") {
            steps {
                echo "this is build stage"
            }
        }
    }
    stages {
        stage("testing") {
            steps {
                echo" this is testing stage"
            }
        }
    }
    stages {
        stage("package") {
            steps {
                echo "this is packageing stage"
            }
        }
    }


}
