pipeline {
    agent any

       environment {
        my_env_var = credentials('ssh_credentials')
    }


    stages {
        stage("Build") {
            steps {
                echo "this is build stage"
        
            }
        }
    
        stage("ENVI") {

        
            steps {
               
               echo 'printenv'
            //    echo '${my_env_var}'

                
            }
        }
        stage("package") {
            steps { 
                echo "this is packaging stage"
                echo "after approval1"
                
            }
        }
    }



post {
    always {
        echo "I always execuste"
    }
    failure {
        echo "I execute on failure"
    }
    success {
        echo  "I execute on success"
    }

}

}
