pipeline {
    agent any
    //  options {
    //     ansiColor('xterm')
    //  }

    stages {
        stage("Build") {
            steps {
                echo "this is build stage"
        
            }
        }
    
        stage("testing") {
            steps {
                
                input "Do you want to  package "

                
            }
        }
        stage("package") {
            steps {
                echo "this is packaging stage"
                echo "after approval"
                
            }
        }
    }



post {
    always {
        echo "I always execuste"
    }
    failure {
        echo "I execute on failure"
    }
    success {
        echo  "I execute on success"
    }

}

}
